#if !canImport(ObjectiveC)
import XCTest

extension CustomLayersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CustomLayersTests = [
        ("testMinibatchStdConcat", testMinibatchStdConcat),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CustomLayersTests.__allTests__CustomLayersTests),
    ]
}
#endif
